# Generated by Django 6.0.4 on 2026-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('idade', models.CharField(max_length=3)),
                ('sexo', models.CharField(max_length=20)),
                ('profissao', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=150)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='Cedro', max_length=100)),
                ('estado', models.CharField(default='CE', max_length=2)),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_de_usuario', models.CharField(choices=[('locador', 'Locador'), ('locatario', 'Locatário')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
