# Generated by Django on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_locacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rede_social_1',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rede_social_2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rede_social_3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
