# Generated by Django on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('quarto', 'Quarto'), ('terreno', 'Terreno')], max_length=50),
        ),
    ]
